Repository embroider-build/embroider, pull requests merged in 2021-10, with the labels that each got.

#989 use babel-import-util
  packages/core/package.json
  packages/core/src/babel-import-adder.ts
  packages/core/src/babel-plugin-inline-hbs.ts
  packages/core/src/template-colocation-plugin.ts
  packages/core/tests/import-adder.test.ts
  yarn.lock
Labels: internal

#990 Invalidate @embroider/macro's babel cache when addon version's change without mutating lock file (e.g. linking)
  packages/macros/src/ember-addon-main.ts
  packages/macros/src/macros-config.ts
  yarn.lock
Labels: bug

#1003 addon-dev: list published files explicitly
  packages/addon-dev/package.json
Labels: bug

#1005 Remove command documentation from `addon-shim` package
  packages/addon-shim/README.md
Labels: documentation
