Repository embroider-build/embroider, pull requests merged in 2021-07, with the labels that each got.

#886 `undefined` does not serialize with broccoli-babel-transpiler
  packages/macros/src/babel/state.ts
  packages/macros/src/macros-config.ts
  tests/app-template/package.json
  tests/scenarios/macro-test.ts
Labels: bug

#890 Drop support for apps that use babel 6
  packages/babel-loader-7/index.js
  packages/babel-loader-7/package.json
  packages/compat/src/v1-app.ts
  packages/core/package.json
  packages/core/src/app.ts
  packages/macros/src/babel/babel-context.ts
  packages/macros/src/babel/each.ts
  packages/macros/src/babel/evaluate-json.ts
  packages/macros/src/babel/get-config.ts
  packages/macros/src/babel/macros-babel-plugin.ts
  packages/macros/tests/babel/eval.test.ts
  packages/shared-internals/src/metadata.ts
  packages/webpack/package.json
  packages/webpack/src/ember-webpack.ts
  test-packages/support/index.ts
  test-packages/support/package.json
  types/babel-core/index.d.ts
  types/babel-core/package.json
  yarn.lock
Labels: breaking

#888 Expose sourceOfConfig to macro config mergers
  packages/macros/src/ember-addon-main.ts
  packages/macros/src/macros-config.ts
  tests/fixtures/macro-sample-addon/index.js
  tests/fixtures/macro-test/ember-cli-build.js
  tests/fixtures/macro-test/tests/integration/components/cross-package-config-test.js
Labels: breaking

#907 Deflate AdjustImportsOptions
  packages/compat/src/compat-app.ts
  packages/compat/src/resolver.ts
  packages/core/src/app.ts
  packages/core/src/babel-plugin-adjust-imports.ts
Labels: enhancement

#904 Fix ember-test-selectors custom adapter for 6.x
  packages/compat/src/compat-adapters/ember-test-selectors.ts
Labels: bug

#900 Only patch `ember-cli-deprecation-workflow` releases before `2.0.0`
  packages/compat/src/compat-adapters/ember-cli-deprecation-workflow.ts
Labels: bug

#899 support inert TemplateLiteral in hbs plugin
  packages/core/src/babel-plugin-inline-hbs.ts
  packages/core/tests/inline-hbs.test.ts
Labels: bug

#912 Use `require` for retrieving the adjust imports info
  packages/compat/src/compat-app.ts
  packages/compat/src/resolver.ts
  packages/core/src/app.ts
  packages/core/src/babel-plugin-adjust-imports.ts
Labels: enhancement

#910 Fix arguments to `preprocessCss` (to match classic build)
  packages/compat/src/v1-app.ts
  tests/fixtures/preprocess-addon/index.js
  tests/scenarios/package.json
  tests/scenarios/preprocess-test.ts
Labels: bug
