Repository embroider-build/embroider, pull requests merged in 2021-08, with the labels that each got.

#915 Reduce memory pressure from compat layer by disabling Heimdall node gathering during OneShotPlugin
  packages/compat/package.json
  packages/compat/src/build-compat-addon.ts
  packages/compat/src/one-shot.ts
  types/heimdalljs/index.d.ts
Labels: enhancement

#917 Improve Heimdall Types
  types/heimdalljs/index.d.ts
Labels: internal

#918 Add `needsCache` and `persistentOutput` to internal broccoli-plugins.
  packages/compat/src/compat-adapters/ember-cli-fastboot.ts
  packages/compat/src/empty-package-tree.ts
  packages/compat/src/one-shot.ts
  packages/compat/src/rewrite-package-json.ts
  packages/compat/src/smoosh-package-json.ts
  packages/compat/src/v1-appboot.ts
  packages/compat/src/v1-config.ts
Labels: enhancement

#913 Bust babel cache if dependencies change so dependencySatisfies is always valid
  packages/core/src/app.ts
  packages/macros/package.json
  packages/macros/src/ember-addon-main.ts
  packages/macros/src/macros-config.ts
  packages/macros/tests/babel/helpers.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/babel-plugin-cache-busting.ts
  tests/fixtures/macro-test/app/controllers/application.js
  tests/fixtures/macro-test/app/templates/application.hbs
  tests/fixtures/macro-test/config/environment.js
  tests/fixtures/macro-test/tests/acceptance/basic-test.js
  tests/scenarios/macro-test.ts
  tests/scenarios/package.json
  yarn.lock
Labels: bug

#843 [hygiene] Volta pin latest node / yarn
  package.json
Labels: internal

#877 [BREAKING] Respect JOBS count if present
  packages/webpack/src/ember-webpack.ts
Labels: breaking
