Repository embroider-build/embroider, pull requests merged in 2021-03, with the labels that each got.

#702 Handle case where node_modules are symlinked
  packages/compat/src/moved-package-cache.ts
Labels: bug

#694 Run importSync transform later, so ember-auto-import can support importSync
  packages/macros/src/babel/macros-babel-plugin.ts
Labels: enhancement

#703 Add 3.20 and 3.24 to list of matrix tests.
  packages/router/config/ember-try.js
  packages/util/config/ember-try.js
  test-packages/macro-sample-addon/config/ember-try.js
Labels: internal

#704 Avoid running CI jobs on both push and pull_request events.
  .github/workflows/ci.yml
Labels: internal

#705 Avoid patching the template compiler on Ember 3.26.
  packages/core/src/patch-template-compiler.ts
Labels: enhancement

#707 Fixup types for newer @babel/types.
  packages/core/src/babel-plugin-adjust-imports.ts
  packages/macros/tests/babel/eval.test.ts
Labels: internal

#710 Fix case where autoRun = false
  packages/compat/src/v1-appboot.ts
Labels: bug

#711 Add release automation setup.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#712 Allow macroCondition inside modifier
  packages/macros/README.md
  packages/macros/src/glimmer/ast-transform.ts
  packages/macros/tests/glimmer/macro-condition.test.ts
  test-packages/macro-tests/package.json
  test-packages/macro-tests/tests/integration/components/macro-if-test.js
  test-packages/support/vendor/README.md
  test-packages/support/vendor/ember-template-compiler.js
  yarn.lock
Labels: enhancement

#713 Avoid monkey patching template compiler for 3.24.3 and 3.25.2+.
  packages/core/src/patch-template-compiler.ts
Labels: enhancement

#706 Remove `ember-cli-htmlbars` dependency in `@embroider/compat`.
  packages/compat/package.json
  packages/compat/src/v1-addon.ts
  yarn.lock
Labels: internal

#716 Add documentation about publicAssetURL to README
  README.md
Labels: documentation

#720 Improve error message when module cannot be found in webpack
  packages/webpack/src/ember-webpack.ts
Labels: enhancement

#743 Migrate from rwjblue/setup-volta to volta-cli/action.
  .github/workflows/ci.yml
  test-packages/eager-engine/package.json
Labels: internal

#742 Improving Windows support
  packages/core/src/app.ts
  packages/core/src/template-compiler-common.ts
  packages/core/src/write-template-compiler.ts
  packages/core/tests/template-compiler-common.test.ts
  packages/shared-internals/src/package-name.ts
Labels: bug
