Repository embroider-build/embroider, pull requests merged in 2021-06, with the labels that each got.

#832 Schedule CI runs daily
  .github/workflows/ci.yml
Labels: internal

#828 Update addon-shim to use ember-auto-import v2 final
  packages/addon-shim/package.json
  yarn.lock
Labels: bug

#840 Run linting in CI before running the full matrix of jobs
  .github/workflows/ci.yml
  test-packages/support/suite-setup-util.ts
Labels: internal

#851 Fix missing exports in package key
  packages/core/package.json
Labels: bug

#852 Drop support for Node 10, 11, 13, and 15.
  packages/addon-shim/package.json
  packages/babel-loader-7/package.json
  packages/compat/package.json
  packages/core/package.json
  packages/hbs-loader/package.json
  packages/macros/package.json
  packages/router/package.json
  packages/shared-internals/package.json
  packages/test-setup/package.json
  packages/util/package.json
  packages/webpack/package.json
Labels: breaking

#853 Better error message when an asset cannot be found in entry file
  packages/compat/src/compat-app.ts
  packages/compat/src/v1-app.ts
Labels: bug

#858 Remove ember-engines version pin
  tests/scenarios/package.json
  yarn.lock
Labels: internal

#860 Ensure all errors are reported when an error occurs in webpack
  packages/webpack/package.json
  packages/webpack/src/ember-webpack.ts
  yarn.lock
Labels: enhancement

#859 Convert macro-test to new test structure
  tests/fixtures/funky-sample-addon/addon/index.js
  tests/fixtures/funky-sample-addon/fake-other-module/index.js
  tests/fixtures/funky-sample-addon/index.js
  tests/fixtures/funky-sample-addon/tests/unit/dummy-app-test.js
  tests/fixtures/macro-test/app/controllers/application.js
  tests/fixtures/macro-test/app/helpers/reflect-addon-config.js
  tests/fixtures/macro-test/app/templates/application.hbs
  tests/fixtures/macro-test/ember-cli-build.js
  tests/fixtures/macro-test/tests/acceptance/basic-test.js
  tests/fixtures/macro-test/tests/index.html
  tests/fixtures/macro-test/tests/integration/components/common-test.js
  tests/fixtures/macro-test/tests/integration/components/cross-package-config-test.js
  tests/fixtures/macro-test/tests/integration/components/dependency-satisfies-test.js
  tests/fixtures/macro-test/tests/integration/components/funky-sample-addon-interopt-test.js
  tests/fixtures/macro-test/tests/integration/components/get-config-test.js
  tests/fixtures/macro-test/tests/integration/components/is-testing-test.js
  tests/fixtures/macro-test/tests/integration/components/macro-if-test.js
  tests/fixtures/macro-test/vendor/apple.js
  tests/fixtures/macro-test/vendor/four.js
  tests/fixtures/macro-test/vendor/one.js
  tests/fixtures/macro-test/vendor/prepend/four.js
  tests/fixtures/macro-test/vendor/prepend/one.js
  tests/fixtures/macro-test/vendor/prepend/order.js
  tests/fixtures/macro-test/vendor/prepend/three.js
  tests/fixtures/macro-test/vendor/prepend/two.js
  tests/fixtures/macro-test/vendor/three.js
  tests/fixtures/macro-test/vendor/two.js
  tests/scenarios/macro-test.ts
  tests/scenarios/package.json
Labels: internal

#864 Add missing typescript devDependency
  packages/addon-shim/package.json
  packages/util/package.json
Labels: internal

#872 Template compiler plugin not removed due to bad path comparison on Windows
  packages/core/src/template-compiler-node.ts
Labels: bug

#865 Enable parallelization of @embroider/macros in non-Embroider builds
  packages/macros/src/ember-addon-main.ts
  packages/macros/src/glimmer/ast-transform.ts
  packages/macros/src/macros-config.ts
  tests/scenarios/macro-test.ts
Labels: bug

#874 Convert `sample-lib` to new test infra
  test-packages/sample-lib/index.js
  test-packages/sample-lib/package.json
  tests/scenarios/fastboot-app-test.ts
  tests/scenarios/package.json
  yarn.lock
Labels: internal

#881 Fix race condition finding the owning package of a given file when using multiple workers
  packages/core/package.json
  packages/shared-internals/package.json
  packages/shared-internals/src/package-cache.ts
  packages/shared-internals/tests/package-cache.test.ts
  packages/webpack/package.json
Labels: bug
