Repository embroider-build/embroider, pull requests merged in 2022-08, with the labels that each got.

#1239 add unique-id to builtInHelpers list
  packages/compat/src/resolver.ts
Labels: enhancement

#1240 Port file assertions to qunit
  packages/addon-dev/src/template-transform-plugin.ts
  test-packages/support/file-assertions.ts
  tests/scenarios/package.json
  tests/scenarios/v2-addon-dev-test.ts
Labels: internal

#1248 Use consistent separator on windows
  packages/compat/src/v1-app.ts
Labels: bug
