Repository embroider-build/embroider, pull requests merged in 2022-03, with the labels that each got.

#1148 Fix `package.json` example in V2 porting guide
  PORTING-ADDONS-TO-V2.md
Labels: documentation

#1152 improve test suite compat
  packages/core/src/app-files.ts
Labels: bug

#1155 Turn ensureSafeComponent into a no-op for class values on Ember 3.25+
  packages/util/addon/index.js
Labels: enhancement
