Repository embroider-build/embroider, pull requests merged in 2023-06, with the labels that each got.

#1458 Add compatible Ember version to README.md
  README.md
Labels: documentation

#1460 expanding EmptyPackage contents
  packages/compat/src/build-compat-addon.ts
  packages/compat/src/empty-package-tree.ts
Labels: bug

#1469 update deprecated (and removed) blacklist config in test app
  tests/fixtures/blacklisted-addon-build-options/ember-cli-build.js
Labels: internal

#1463 fix resolution of files with .hbs extensions
  packages/core/src/module-resolver.ts
  tests/scenarios/core-resolver-test.ts
Labels: bug

#1476 Delete .DS_Store
  packages/router/src/.DS_Store
Labels: internal
