Repository embroider-build/embroider, pull requests merged in 2023-07, with the labels that each got.

#1503 less aggressive realpathSync
  packages/shared-internals/src/rewritten-package-cache.ts
Labels: bug

#1507 fix(macros-readme): fix isTesting, isDevelopingApp typos
  packages/macros/README.md
Labels: documentation

#1509 All addons may need emberVirtualPeerDep handling
  packages/core/src/module-resolver.ts
Labels: bug

#1510 Replace rollup-plugin-ts with @rollup/plugin-typescript
  packages/router/babel.config.json
  packages/router/package.json
  packages/router/rollup.config.mjs
  packages/router/tsconfig.json
  pnpm-lock.yaml
  tests/scenarios/package.json
  tests/scenarios/v2-addon-dev-typescript-test.ts
Labels: internal

#1522 format resolver.json more nicely
  packages/compat/src/compat-app-builder.ts
Labels: internal

#1528 Restore older node support
  tests/scenarios/core-resolver-test.ts
  tests/scenarios/shared-internals-test.ts
  tsconfig.json
Labels: bug

#1537 Update babel-import-util
  packages/compat/package.json
  packages/core/package.json
  packages/macros/package.json
  packages/shared-internals/package.json
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/package.json
Labels: internal

#1536 Generate per-package implicit-modules imports
  packages/compat/src/babel-plugin-adjust-imports.ts
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/dependency-rules.ts
  packages/core/src/index.ts
  packages/core/src/module-resolver.ts
  packages/core/src/resolver-loader.ts
  packages/core/src/virtual-content.ts
  packages/shared-internals/src/package.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  packages/webpack/src/virtual-loader.ts
  packages/webpack/src/webpack-resolver-plugin.ts
  test-packages/support/audit-assertions.ts
  test-packages/support/index.ts
  tests/scenarios/compat-namespaced-app-test.ts
  tests/scenarios/compat-renaming-test.ts
Labels: bug

#1538 Removing workaround
  packages/core/src/module-resolver.ts
Labels: internal

#1540 remove an overridden dependency
  package.json
  pnpm-lock.yaml
Labels: internal

#1544 Bugfix: contextual staticHelpers in subexpression position
  packages/compat/src/resolver-transform.ts
  tests/scenarios/compat-resolver-test.ts
Labels: bug

#1548 optional ES-module compatibility setting
  packages/compat/src/compat-app-builder.ts
  packages/compat/tests/audit.test.ts
  packages/core/src/module-resolver.ts
  packages/core/src/options.ts
  packages/core/src/virtual-content.ts
  packages/macros/src/babel/state.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/paths.ts
  packages/shared-internals/src/template-colocation-plugin.ts
  pnpm-lock.yaml
  tests/scenarios/compat-namespaced-app-test.ts
  tests/scenarios/compat-renaming-test.ts
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
Labels: enhancement

#1552 add --access=public to npm publish unstable
  test-packages/unstable-release/publish.js
Labels: internal

#1518 add a basic implementation of the gjs rollup plugin
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/addon-dev/src/rollup.ts
  pnpm-lock.yaml
  tests/scenarios/package.json
  tests/scenarios/v2-addon-dev-test.ts
Labels: enhancement

#1492 Make release idempotent (+dry-run)
  pnpm-lock.yaml
  test-packages/release/package.json
  test-packages/release/src/cli.ts
  test-packages/release/src/publish.ts
Labels: internal

#1558 Simplification of gjs and hbs handling in addon-dev
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/addon-dev/src/rollup-hbs-plugin.ts
  pnpm-lock.yaml
  tests/scenarios/v2-addon-dev-test.ts
Labels: breaking

#1560 Fix rewritten package cache encapsulation
  packages/babel-loader-8/package.json
  packages/core/src/module-resolver.ts
  packages/macros/src/babel/get-config.ts
  packages/macros/src/babel/state.ts
  packages/macros/src/glimmer/get-config.ts
  packages/macros/src/macros-config.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  pnpm-lock.yaml
  tests/scenarios/core-resolver-test.ts
Labels: bug
