Repository embroider-build/embroider, pull requests merged in 2023-11, with the labels that each got.

#1603 Add some action items to the peer errors when node_modules is messed up
  packages/compat/src/standalone-addon-build.ts
Labels: documentation

#1655 fix node version for @embroider/util
  packages/util/ember-cli-build.js
  packages/util/package.json
  tests/scenarios/util-test.ts
Labels: bug

#1666 unpin json-stable-stringify
  package.json
  pnpm-lock.yaml
Labels: internal

#1668 prepare release
  .release-plan.json
  CHANGELOG.md
  packages/compat/package.json
  packages/core/package.json
Labels: internal

#1670 Fix looping for unchanged files
  packages/core/src/module-resolver.ts
Labels: bug

#1673 allow apps to disable the decorator transforms
  packages/compat/src/compat-app.ts
Labels: enhancement

#1652 create new @embroider/reverse-exports package
  .eslintignore
  .prettierignore
  packages/reverse-exports/.gitignore
  packages/reverse-exports/jest.config.js
  packages/reverse-exports/package.json
  packages/reverse-exports/src/index.ts
  packages/reverse-exports/tests/reverse-exports.test.ts
  pnpm-lock.yaml
Labels: enhancement

#1676 fix single asterisk replacement in reverse-exports
  packages/reverse-exports/package.json
  packages/reverse-exports/src/index.ts
  packages/reverse-exports/tests/reverse-exports.test.ts
  pnpm-lock.yaml
Labels: bug

#1684 Workaround typescript regression in router package
  packages/router/package.json
  pnpm-lock.yaml
Labels: bug
