Repository embroider-build/embroider, pull requests merged in 2023-12, with the labels that each got.

#1693 Add broccoli-side-watch package
  packages/broccoli-side-watch/README.md
  packages/broccoli-side-watch/index.js
  packages/broccoli-side-watch/package.json
  pnpm-lock.yaml
Labels: enhancement

#1698 Use release plan
  .github/workflows/ci.yml
  .github/workflows/publish-stable.yml
  .github/workflows/release-plan-preview.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
  test-packages/release/.gitignore
  test-packages/release/package.json
  test-packages/release/src/change-parser.ts
  test-packages/release/src/cli.ts
  test-packages/release/src/gather-changes.ts
  test-packages/release/src/highlight.ts
  test-packages/release/src/interdep.ts
  test-packages/release/src/plan.ts
  test-packages/release/src/prepare.ts
  test-packages/release/src/publish.ts
  test-packages/release/src/utils.ts
Labels: internal

#1691 Move fix for @ember-data/debug into virtualPeerDeps
  packages/compat/src/compat-adapters/@ember-data/debug.ts
  packages/compat/src/compat-adapters/@ember-data/store.ts
  packages/shared-internals/src/ember-standard-modules.ts
Labels: internal

#1700 Merge stable into main
  .github/workflows/publish-stable.yml
  .github/workflows/release-plan-preview.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
  test-packages/release/.gitignore
  test-packages/release/package.json
  test-packages/release/src/change-parser.ts
  test-packages/release/src/cli.ts
  test-packages/release/src/gather-changes.ts
  test-packages/release/src/highlight.ts
  test-packages/release/src/interdep.ts
  test-packages/release/src/plan.ts
  test-packages/release/src/prepare.ts
  test-packages/release/src/publish.ts
  test-packages/release/src/utils.ts
Labels: internal

#1703 Disable chokidar polling override in tests
  tests/scenarios/helpers/v2-addon.ts
Labels: internal

#1704 add correct extensions to optimizeDeps() config
  packages/vite/src/optimize-deps.ts
  packages/vite/tests/optimize-deps.test.ts
Labels: enhancement

#1712 Merge stable
  packages/macros/tests/babel/helpers.ts
  pnpm-lock.yaml
Labels: internal

#1707 improved resolver logging
  packages/core/src/module-resolver.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/request.ts
  packages/webpack/src/webpack-resolver-plugin.ts
Labels: enhancement

#1686 Resolver bugfixes
  packages/compat/src/audit.ts
  packages/compat/src/compat-app-builder.ts
  packages/compat/tests/audit.test.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/vite/src/addons.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/request.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/webpack-resolver-plugin.ts
  test-packages/support/suite-setup-util.ts
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
  tests/scenarios/jest-suites-test.ts
Labels: bug

#1697 Hide base path from public URL of rollup-public-assets
  packages/addon-dev/src/rollup-public-assets.ts
Labels: breaking

#1692 force importSync to always be eager
  packages/compat/src/compat-adapters/ember-fetch.ts
  packages/compat/src/compat-app-builder.ts
  packages/macros/src/babel/each.ts
  packages/macros/src/babel/macros-babel-plugin.ts
  packages/macros/src/babel/state.ts
  packages/macros/src/macros-config.ts
  packages/macros/tests/babel/import-sync.test.ts
  packages/webpack/src/ember-webpack.ts
  pnpm-lock.yaml
  tests/fixtures/macro-sample-addon/app/helpers/reflect-updated-config.js
  tests/fixtures/macro-sample-addon/tests/dummy/app/helpers/reflect-updated-config.js
  tests/scenarios/package.json
  tests/scenarios/scenarios.ts
  tests/scenarios/static-app-test.ts
  tests/scenarios/util-test.ts
Labels: breaking

#1706 Support engine's lazyLoading boolean config
  packages/compat/src/v1-addon.ts
Labels: bug

#1716 update release-plan
  package.json
  pnpm-lock.yaml
Labels: internal

#1688 Fix branch elimination for `macroDependencySatisfies`
  packages/macros/src/glimmer/ast-transform.ts
  packages/macros/tests/glimmer/dependency-satisfies.test.ts
Labels: bug

#1717 Always load ember-testing package eagerly
  packages/compat/src/compat-adapters/ember-source.ts
  packages/compat/src/compat-app-builder.ts
Labels: bug

#1723 Sync stable->main
  .release-plan.json
  CHANGELOG.md
  packages/addon-dev/package.json
  packages/compat/package.json
  packages/compat/src/compat-adapters/ember-source.ts
  packages/compat/src/compat-app-builder.ts
  packages/core/package.json
  packages/macros/package.json
  packages/macros/src/glimmer/ast-transform.ts
  packages/macros/tests/glimmer/dependency-satisfies.test.ts
Labels: internal

#1729 remove missing import from vite index
  packages/vite/index.mjs
Labels: bug

#1731 Vite fixes
  pnpm-lock.yaml
  tests/vite-app/app/adapters/post.js
  tests/vite-app/app/app.js
  tests/vite-app/babel.config.js
  tests/vite-app/package.json
  tests/vite-app/public/posts/1.json
  tests/vite-app/vite.config.mjs
Labels: bug

#1642 Allow for more flexible addon-dev appReexports
  packages/addon-dev/src/rollup-app-reexports.ts
  packages/addon-dev/src/rollup.ts
  tests/scenarios/v2-addon-dev-typescript-test.ts
Labels: enhancement

#1740 enable vite windows tests
  test-packages/support/suite-setup-util.ts
  tests/scenarios/vite-app-test.ts
Labels: internal

#1743 Don't rely on htmlbars internals
  packages/compat/src/compat-app.ts
  packages/compat/src/prepare-htmlbars-ast-plugins.ts
  packages/compat/src/v1-addon.ts
  types/ember-cli-htmlbars/index.d.ts
  types/ember-cli-htmlbars/package.json
Labels: bug
