Repository embroider-build/embroider, pull requests merged in 2023-09, with the labels that each got.

#1600 Fix relative import path of assets for non-entrypoint modules
  packages/addon-dev/src/rollup-keep-assets.ts
Labels: bug

#1607 Add v2 addon FAQs
  README.md
  docs/addon-author-guide.md
  docs/v2-faq.md
Labels: documentation

#1609 Fix WrappedPackage caching for app
  packages/shared-internals/src/rewritten-package-cache.ts
Labels: bug

#1611 performance: avoid paying decodeFastbootSwitch regex cost unless needed
  packages/core/src/virtual-content.ts
Labels: enhancement

#1613 More v2 addon FAQs
  docs/v2-faq.md
Labels: documentation

#1604 add staticEmberSource to the readme example
  README.md
Labels: documentation

#1597 Fix HTML content failing to update
  packages/webpack/src/ember-webpack.ts
Labels: bug
