Repository embroider-build/embroider, pull requests merged in 2024-10, with the labels that each got.

#2082 Hide base path from public URL of rollup-public-assets
  packages/addon-dev/src/rollup-public-assets.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: breaking

#2137 Delete test-packages/sample-transforms/tests
  test-packages/sample-transforms/tests/dummy/app/app.js
  test-packages/sample-transforms/tests/dummy/app/components/.gitkeep
  test-packages/sample-transforms/tests/dummy/app/controllers/.gitkeep
  test-packages/sample-transforms/tests/dummy/app/helpers/.gitkeep
  test-packages/sample-transforms/tests/dummy/app/index.html
  test-packages/sample-transforms/tests/dummy/app/models/.gitkeep
  test-packages/sample-transforms/tests/dummy/app/resolver.js
  test-packages/sample-transforms/tests/dummy/app/router.js
  test-packages/sample-transforms/tests/dummy/app/routes/.gitkeep
  test-packages/sample-transforms/tests/dummy/app/styles/app.css
  test-packages/sample-transforms/tests/dummy/app/templates/application.hbs
  test-packages/sample-transforms/tests/dummy/app/templates/components/.gitkeep
  test-packages/sample-transforms/tests/dummy/config/environment.js
  test-packages/sample-transforms/tests/dummy/config/optional-features.json
  test-packages/sample-transforms/tests/dummy/config/targets.js
  test-packages/sample-transforms/tests/dummy/public/robots.txt
  test-packages/sample-transforms/tests/helpers/.gitkeep
  test-packages/sample-transforms/tests/index.html
  test-packages/sample-transforms/tests/integration/.gitkeep
  test-packages/sample-transforms/tests/test-helper.js
  test-packages/sample-transforms/tests/unit/.gitkeep
Labels: internal

#2138 Delete unneeded util files
  packages/util/tests/dummy/app/components/.gitkeep
  packages/util/tests/dummy/app/controllers/.gitkeep
  packages/util/tests/dummy/app/helpers/.gitkeep
  packages/util/tests/dummy/app/index.html
  packages/util/tests/dummy/app/models/.gitkeep
  packages/util/tests/dummy/app/routes/.gitkeep
  packages/util/tests/integration/.gitkeep
  packages/util/tests/unit/.gitkeep
Labels: internal

#2131 Rename @embroider/core/entrypoint to @embroider/virtual/compat-modules
  packages/core/package.json
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-entrypoint.ts
  packages/core/types/virtual/index.d.ts
  packages/core/types/virtual/index.js
  tests/addon-template/tests/dummy/app/app.js
  tests/app-template/app/app.js
  tests/scenarios/compat-renaming-test.ts
  tests/ts-app-template/app/app.ts
  tests/ts-app-template/types/ts-app-template/entry.d.ts
  tests/ts-app-template/types/ts-app-template/index.d.ts
Labels: enhancement

#2139 Rename vendor.* to be from @embroider/virtual instead of @embroider/core
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-entrypoint.ts
  packages/vite/src/resolver.ts
  tests/addon-template/tests/dummy/index.html
  tests/addon-template/tests/index.html
  tests/app-template/index.html
  tests/app-template/tests/index.html
  tests/fixtures/macro-sample-addon/tests/dummy/app/index.html
  tests/fixtures/macro-sample-addon/tests/index.html
  tests/fixtures/macro-test/tests/index.html
  tests/scenarios/compat-addon-classic-features-test.ts
  tests/ts-app-template/index.html
  tests/ts-app-template/tests/index.html
Labels: enhancement

#2135 Capture new optimized deps
  packages/core/src/virtual-entrypoint.ts
  packages/vite/src/resolver.ts
  pnpm-lock.yaml
  test-packages/support/audit-assertions.ts
  test-packages/support/suite-setup-util.ts
  tests/scenarios/v2-addon-test.ts
  tests/scenarios/vite-dep-optimizer-test.ts
Labels: bug

#2142 fixing test suite for ember >= 6
  pnpm-lock.yaml
  tests/scenarios/static-app-test.ts
Labels: internal

#2133 Bugfix template tag codemod ts
  README.md
  packages/compat/package.json
  packages/compat/src/resolver-transform.ts
  packages/compat/src/template-tag-codemod.ts
  pnpm-lock.yaml
  tests/scenarios/template-tag-codemod-test.ts
Labels: bug

#2141 Add better broccoli-side-watch package
  .eslintignore
  .prettierignore
  packages/broccoli-side-watch/.gitignore
  packages/broccoli-side-watch/README.md
  packages/broccoli-side-watch/jest.config.js
  packages/broccoli-side-watch/package.json
  packages/broccoli-side-watch/src/index.ts
  packages/broccoli-side-watch/tests/side-watch.test.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/watch-utils.ts
  packages/shared-internals/tests/watch-utils.test.ts
  pnpm-lock.yaml
Labels: enhancement

#2148 Fix broken default export when required from CJS
  packages/broccoli-side-watch/src/index.ts
Labels: bug

#2143 Vite hbs plugin should return resolutions
  packages/vite/src/hbs.ts
Labels: bug

#2151 Fix hbs plugin not resolving .hbs due to broken Regex
  packages/shared-internals/src/colocation.ts
  packages/shared-internals/tests/colocation.test.ts
Labels: bug

#2158 Add a new option for addon-shim to pass config to ember-auto-import
  packages/addon-shim/src/index.ts
Labels: enhancement
