Repository embroider-build/embroider, pull requests merged in 2024-04, with the labels that each got.

#1867 add a namespace option for public-assets plugin
  docs/v2-faq.md
  packages/addon-dev/README.md
  packages/addon-dev/src/rollup-public-assets.ts
  packages/addon-dev/src/rollup.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: enhancement

#1856 Compile Hbs route templates correctly
  docs/v2-faq.md
  packages/addon-dev/src/rollup-hbs-plugin.ts
  packages/addon-dev/src/rollup.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/paths.ts
  packages/shared-internals/src/template-colocation-plugin.ts
  pnpm-lock.yaml
  tests/scenarios/v2-addon-dev-test.ts
Labels: enhancement

#1872 Merge stable
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .release-plan.json
  CHANGELOG.md
  docs/v2-faq.md
  package.json
  packages/addon-dev/README.md
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-hbs-plugin.ts
  packages/addon-dev/src/rollup-public-assets.ts
  packages/addon-dev/src/rollup.ts
  packages/compat/package.json
  packages/compat/src/resolver-transform.ts
  packages/core/package.json
  packages/macros/package.json
  packages/macros/src/babel/evaluate-json.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/paths.ts
  packages/shared-internals/src/template-colocation-plugin.ts
  packages/util/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: internal

#1874 with namespace in publicAssets don't include path
  packages/addon-dev/README.md
  packages/addon-dev/src/rollup-public-assets.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: bug

#1877 Command Watcher
  packages/vite/src/assets.ts
  pnpm-lock.yaml
  tests/addon-template/package.json
  tests/addon-template/vite.config.mjs
  tests/scenarios/compat-dummy-app-test.ts
  tests/scenarios/helpers/command-watcher.ts
  tests/scenarios/package.json
  tests/scenarios/watch-mode-test.ts
Labels: internal

#1879 Delete vite app from test scenarios
  tests/app-template/vite.config.mjs
  tests/scenarios/scenarios.ts
  tests/scenarios/vite-app-test.ts
  tests/vite-app/.editorconfig
  tests/vite-app/.ember-cli
  tests/vite-app/.eslintignore
  tests/vite-app/.eslintrc.js
  tests/vite-app/.github/workflows/ci.yml
  tests/vite-app/.gitignore
  tests/vite-app/.prettierignore
  tests/vite-app/.prettierrc.js
  tests/vite-app/.stylelintignore
  tests/vite-app/.stylelintrc.js
  tests/vite-app/.template-lintrc.js
  tests/vite-app/.watchmanconfig
  tests/vite-app/README.md
  tests/vite-app/app/app.js
  tests/vite-app/app/components/.gitkeep
  tests/vite-app/app/components/example.hbs
  tests/vite-app/app/components/example.js
  tests/vite-app/app/components/fancy.gts
  tests/vite-app/app/components/fancy2.gjs
  tests/vite-app/app/components/old/component.js
  tests/vite-app/app/components/old/template.hbs
  tests/vite-app/app/controllers/.gitkeep
  tests/vite-app/app/helpers/.gitkeep
  tests/vite-app/app/index.html
  tests/vite-app/app/models/.gitkeep
  tests/vite-app/app/router.js
  tests/vite-app/app/routes/.gitkeep
  tests/vite-app/app/routes/application.ts
  tests/vite-app/app/styles/app.css
  tests/vite-app/app/templates/application.hbs
  tests/vite-app/babel.config.js
  tests/vite-app/config/ember-cli-update.json
  tests/vite-app/config/environment.js
  tests/vite-app/config/optional-features.json
  tests/vite-app/config/targets.js
  tests/vite-app/ember-cli-build.js
  tests/vite-app/package.json
  tests/vite-app/public/robots.txt
  tests/vite-app/scripts/run-tests.mjs
  tests/vite-app/testem.js
  tests/vite-app/tests/acceptance/app-route-test.js
  tests/vite-app/tests/helpers/index.js
  tests/vite-app/tests/index.html
  tests/vite-app/tests/integration/.gitkeep
  tests/vite-app/tests/integration/example-test.js
  tests/vite-app/tests/integration/fany-test-gjs.gjs
  tests/vite-app/tests/integration/fany-test.gts
  tests/vite-app/tests/integration/fany2-test.js
  tests/vite-app/tests/setup-harness.js
  tests/vite-app/tests/test-helper.js
  tests/vite-app/tests/unit/.gitkeep
  tests/vite-app/vite.config.mjs
Labels: internal

#1868 Adjusting `@embroider/webpack` to use `@babel/preset-env` to avoid critical security audit
  packages/webpack/package.json
  pnpm-lock.yaml
Labels: breaking

#1881 Cleanup stage2 emitting of synthesized styles
  packages/compat/src/compat-app-builder.ts
  pnpm-lock.yaml
  tests/scenarios/compat-namespaced-app-test.ts
  tests/scenarios/preprocess-test.ts
Labels: internal

#1858 Add support for `{{unless}}` to the `macroCondition` macro
  packages/macros/src/glimmer/ast-transform.ts
  packages/macros/src/glimmer/macro-condition.ts
  tests/fixtures/macro-test/tests/integration/components/macro-unless-test.js
Labels: enhancement

#1885 Fix pre support in portable babel launcher
  package.json
  packages/core/src/portable-babel-launcher.ts
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/stage1-test.ts
Labels: bug

#1886 Merge stable into main
  CHANGELOG.md
  package.json
  packages/addon-dev/README.md
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-public-assets.ts
  packages/compat/package.json
  packages/core/package.json
  packages/core/src/portable-babel-launcher.ts
  packages/macros/package.json
  packages/macros/src/glimmer/ast-transform.ts
  packages/macros/src/glimmer/macro-condition.ts
  packages/test-setup/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  tests/fixtures/macro-test/tests/integration/components/macro-unless-test.js
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/stage1-test.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: internal

#1801 Module resolver: virtualize vendor.js
  packages/compat/src/compat-app-builder.ts
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-content.ts
  packages/core/src/virtual-vendor.ts
  packages/vite/src/resolver.ts
  test-packages/support/suite-setup-util.ts
  tests/scenarios/compat-addon-classic-features-test.ts
Labels: enhancement

#1890 Add more tests virtual files
  tests/scenarios/compat-addon-classic-features-test.ts
Labels: internal

#1882 Splitting reusable module visitor out of Audit
  packages/compat/src/audit.ts
  packages/compat/src/module-visitor.ts
  packages/compat/tests/audit.test.ts
  test-packages/support/audit-assertions.ts
  tests/scenarios/compat-exclude-dot-files-test.ts
  tests/scenarios/compat-renaming-test.ts
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/compat-template-colocation-test.ts
Labels: internal
