Repository embroider-build/embroider, pull requests merged in 2024-01, with the labels that each got.

#1714 update scenario-tester
  packages/compat/package.json
  packages/macros/package.json
  packages/macros/tests/babel/dependency-satisfies.test.ts
  packages/macros/tests/babel/macro-condition.test.ts
  packages/macros/tests/glimmer/dependency-satisfies.test.ts
  packages/macros/tests/glimmer/macro-condition.test.ts
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
  tests/scenarios/package.json
Labels: internal

#1653 Refactor embroider-implicit-modules export pojo
  packages/compat/src/compat-app-builder.ts
  packages/core/src/virtual-content.ts
  pnpm-lock.yaml
  test-packages/support/audit-assertions.ts
  tests/scenarios/app-config-environment-test.ts
  tests/scenarios/compat-renaming-test.ts
  tests/scenarios/engines-test.ts
  tests/scenarios/glimmer-tracking-test.ts
  tests/scenarios/macro-test.ts
  tests/scenarios/package.json
  tests/scenarios/scenarios.ts
  tests/scenarios/stage1-test.ts
  tests/scenarios/util-test.ts
  tests/scenarios/v2-addon-dev-test.ts
  tests/scenarios/v2-addon-dev-typescript-test.ts
Labels: breaking

#1758 Make template-colocation-plugin idempotent
  packages/shared-internals/src/template-colocation-plugin.ts
Labels: bug

#1768 docs(porting addons to v2): change the recommended package manager to pnpm
  docs/porting-addons-to-v2.md
Labels: documentation

#1771 Simplify vite-app template
  pnpm-lock.yaml
  tests/scenarios/vite-app-test.ts
  tests/vite-app/app/adapters/post.js
  tests/vite-app/app/models/post.js
  tests/vite-app/app/routes/application.ts
  tests/vite-app/package.json
  tests/vite-app/public/posts/1.json
Labels: internal

#1775 Docs(peer deps resolution issues): mentions pnpm-dedupe and add links
  docs/peer-dependency-resolution-issues.md
Labels: documentation

#1772 Docs porting addons to v2 co location
  docs/porting-addons-to-v2.md
Labels: documentation
