Repository embroider-build/embroider, pull requests merged in 2024-12, with the labels that each got.

#2187 bundle up vite plugins in a nicer way
  packages/vite/index.mjs
  packages/vite/src/classic-ember-support.ts
  packages/vite/src/ember.ts
  tests/app-template/vite.config.mjs
  tests/scenarios/v2-addon-dev-test.ts
Labels: enhancement

#2197 Further simplify ModuleRequest API
  packages/core/src/module-request.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/request.ts
  packages/webpack/src/webpack-resolver-plugin.ts
Labels: internal

#2195 read your browser targets from config/targets.js automatically
  packages/vite/package.json
  packages/vite/src/classic-ember-support.ts
  pnpm-lock.yaml
Labels: enhancement

#2209 Eliminate 'ignored' case from module resolver
  packages/core/src/module-request.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/webpack-resolver-plugin.ts
Labels: bug

#2200 Add rollup declarations plugin
  packages/addon-dev/jest.config.js
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-declarations.ts
  packages/addon-dev/src/rollup.ts
  packages/addon-dev/tests/declarations.test.ts
  pnpm-lock.yaml
Labels: enhancement

#2198 Virtual response namespace unification
  packages/core/src/index.ts
  packages/core/src/module-request.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/core/src/virtual-content.ts
  packages/core/src/virtual-entrypoint.ts
  packages/core/src/virtual-route-entrypoint.ts
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/package-cache.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/request.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/webpack-resolver-plugin.ts
  tests/scenarios/compat-route-split-test.ts
  tests/scenarios/core-resolver-test.ts
Labels: internal

#2217 Fix declarations plugin to cover import()
  packages/addon-dev/src/rollup-declarations.ts
  packages/addon-dev/tests/declarations.test.ts
Labels: bug

#2216 Simplify virtual content rendering
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/core/src/virtual-content.ts
  packages/core/src/virtual-entrypoint.ts
  packages/core/src/virtual-route-entrypoint.ts
  packages/core/src/virtual-test-support-styles.ts
  packages/core/src/virtual-test-support.ts
  packages/core/src/virtual-vendor-styles.ts
  packages/core/src/virtual-vendor.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/request.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/virtual-loader.ts
Labels: internal
