Repository embroider-build/embroider, pull requests merged in 2024-05, with the labels that each got.

#1899 typescript upgrade
  package.json
  packages/addon-dev/package.json
  packages/addon-shim/package.json
  packages/compat/package.json
  packages/core/package.json
  packages/hbs-loader/package.json
  packages/macros/package.json
  packages/router/package.json
  packages/router/types/embroider__router/index.d.ts
  packages/shared-internals/package.json
  packages/util/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  tests/scenarios/package.json
  tests/ts-app-template/package.json
  tests/ts-app-template/types/ts-app-template/index.d.ts
Labels: internal

#1908 update tests to follow newer babel-plugin-ember-template-compiilation
  pnpm-lock.yaml
  tests/scenarios/stage1-test.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: internal

#1907 Make ember-source compat adapter tolerant of upcoming ember-source changes
  packages/compat/src/compat-adapters/ember-source.ts
Labels: enhancement

#1901 [addon-shim]: Narrowed down broccoli trees for optimized file watching
  packages/addon-shim/package.json
  packages/addon-shim/src/index.ts
  pnpm-lock.yaml
Labels: bug

#1912 update all github actions to remove warnings about node version
  .github/actions/setup/action.yml
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  packages/util/.github/workflows/ci.yml
  tests/addon-template/.github/workflows/ci.yml
Labels: internal

#1900 vite: change ext-es format
  packages/core/src/virtual-content.ts
  tests/scenarios/compat-renaming-test.ts
Labels: bug

#1920 New `index.html` format - `test-support.js`
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/core/src/ember-html.ts
  test-packages/sample-transforms/tests/index.html
  tests/addon-template/tests/index.html
  tests/app-template/tests/index.html
  tests/fixtures/macro-test/tests/index.html
  tests/ts-app-template/tests/index.html
Labels: enhancement

#1913 virtualise engine styles with their vendor styles
  packages/compat/src/compat-app-builder.ts
  packages/core/src/asset.ts
  packages/core/src/index.ts
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-vendor-styles.ts
Labels: enhancement

#1919 improve audit tests
  packages/compat/src/http-audit.ts
  test-packages/support/audit-assertions.ts
  tests/scenarios/helpers/command-watcher.ts
Labels: internal

#1779 Virtual entry point
  package.json
  packages/compat/src/compat-app-builder.ts
  packages/compat/tests/audit.test.ts
  packages/core/package.json
  packages/core/src/app-files.ts
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-content.ts
  packages/core/src/virtual-entrypoint.ts
  packages/core/src/virtual-route-entrypoint.ts
  packages/shared-internals/src/package-cache.ts
  patches/ember-source@5.8.0.patch
  pnpm-lock.yaml
  tests/fixtures/engines-host-app/tests/acceptance/basics-test.js
  tests/scenarios/compat-exclude-dot-files-test.ts
  tests/scenarios/compat-renaming-test.ts
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/compat-route-split-test.ts
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/compat-template-colocation-test.ts
  tests/scenarios/core-resolver-test.ts
  tests/scenarios/engines-test.ts
  tests/scenarios/fastboot-app-test.ts
  tests/scenarios/package.json
  tests/scenarios/scenarios.ts
  tests/scenarios/watch-mode-test.ts
Labels: enhancement

#1922 New `index.html` format - entrypoint
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/core/src/ember-html.ts
  packages/util/tests/dummy/app/index.html
  test-packages/sample-transforms/tests/dummy/app/index.html
  test-packages/sample-transforms/tests/index.html
  tests/addon-template/tests/dummy/app/index.html
  tests/addon-template/tests/index.html
  tests/app-template/app/index.html
  tests/app-template/tests/index.html
  tests/fixtures/macro-test/tests/index.html
  tests/scenarios/compat-addon-classic-features-test.ts
  tests/scenarios/compat-app-html-attributes-test.ts
  tests/ts-app-template/app/index.html
  tests/ts-app-template/tests/index.html
Labels: enhancement

#1927 simplify virtual entrypoint
  packages/core/src/virtual-entrypoint.ts
Labels: internal

#1924 virtualise test entrypoint
  packages/compat/src/compat-app-builder.ts
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-content.ts
  packages/core/src/virtual-test-entrypoint.ts
Labels: enhancement

#1925 New `index.html` format - app css
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/core/src/ember-html.ts
  packages/util/tests/dummy/app/index.html
  test-packages/sample-transforms/tests/dummy/app/index.html
  test-packages/sample-transforms/tests/index.html
  tests/addon-template/tests/dummy/app/index.html
  tests/addon-template/tests/index.html
  tests/app-template/app/index.html
  tests/app-template/tests/index.html
  tests/fixtures/macro-test/tests/index.html
  tests/scenarios/compat-addon-classic-features-test.ts
  tests/ts-app-template/app/index.html
  tests/ts-app-template/tests/index.html
Labels: enhancement

#1926 New `index.html`- format test-entrypoint
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/core/src/ember-html.ts
  test-packages/sample-transforms/tests/index.html
  tests/addon-template/tests/index.html
  tests/app-template/tests/index.html
  tests/fixtures/macro-test/tests/index.html
  tests/ts-app-template/tests/index.html
Labels: enhancement

#1933 Clean up compat app builder
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/core/src/asset.ts
  packages/core/src/ember-html.ts
  packages/core/src/index.ts
Labels: enhancement

#1934 Update app-template
  pnpm-lock.yaml
  tests/app-template/package.json
Labels: internal

#1935 output macros-config.json and _babel_config_ in the .embroider folder
  packages/compat/src/audit.ts
  packages/compat/src/compat-app-builder.ts
  packages/core/src/virtual-entrypoint.ts
  packages/vite/src/esbuild-resolver.ts
  test-packages/support/transpiler.ts
  tests/addon-template/babel.config.cjs
  tests/app-template/babel.config.cjs
  tests/ts-app-template-classic/babel.config.cjs
  tests/ts-app-template/babel.config.cjs
Labels: enhancement

#1937 only register v2 addons with parent addons
  packages/addon-shim/src/index.ts
Labels: bug

#1939 Output `_babel_filter_.js` in the `.embroider` folder
  packages/compat/src/compat-app-builder.ts
  test-packages/support/transpiler.ts
Labels: enhancement

#1940 only register v2 addons with parent addons
  packages/addon-shim/src/index.ts
Labels: bug

#1943 Merge stable into main
  .github/workflows/ci.yml
  CHANGELOG.md
  packages/addon-shim/package.json
Labels: internal

#1949 Fix ownerOfFile bug on windows
  package.json
  packages/shared-internals/src/package-cache.ts
  pnpm-lock.yaml
  test-packages/support/suite-setup-util.ts
  tests/scenarios/util-test.ts
Labels: bug

#1945 avoid loading of lazy engines when generating linkto urls for routes
  packages/router/src/index.ts
Labels: bug
