Repository embroider-build/embroider, pull requests merged in 2024-08, with the labels that each got.

#1936 remove auto-upgraded from app package.json and add a basic exports block
  packages/compat/src/compat-app-builder.ts
  packages/core/src/module-resolver.ts
  packages/shared-internals/src/package.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  packages/shared-internals/src/template-colocation-plugin.ts
  tests/app-template/package.json
  tests/ts-app-template/package.json
Labels: enhancement

#2061 Adjusting reverse-exports API
  packages/core/src/module-resolver.ts
  packages/reverse-exports/src/index.ts
  packages/reverse-exports/tests/reverse-exports.test.ts
Labels: internal

#2067 codemod fixes
  packages/compat/src/template-tag-codemod.ts
Labels: bug

#2076 [Stable]: Follow upstream type change from webpack
  packages/webpack/src/ember-webpack.ts
Labels: internal

#2075 Update ember standard modules to include @ember/renderer and @ember/-internals and ember-testing
  packages/shared-internals/src/ember-standard-modules.ts
Labels: bug
