Repository embroider-build/embroider, pull requests merged in 2024-06, with the labels that each got.

#1954 reset version of config-meta-loader to 0.0.0
  packages/config-meta-loader/package.json
Labels: internal

#1946 remove the ember-addon keyword from rewritten app
  package.json
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/standalone-addon-build.ts
  packages/core/src/module-resolver.ts
  packages/macros/src/babel/macros-babel-plugin.ts
  packages/shared-internals/src/babel-filter.ts
  packages/shared-internals/src/dep-validation.ts
  packages/shared-internals/src/package.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  pnpm-lock.yaml
Labels: breaking

#1972 Hide base path from public URL of rollup-public-assets
  packages/addon-dev/src/rollup-public-assets.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: breaking

#1975 Stop using "#with" in macro tests
  packages/macros/tests/glimmer/get-config.test.ts
  tests/fixtures/macro-test/tests/integration/components/common-test.js
  tests/fixtures/macro-test/tests/integration/components/get-config-test.js
  tests/scenarios/compat-resolver-test.ts
Labels: bug

#1977 Fix modifier removal for "unless (macroCondition ...)"
  packages/macros/src/glimmer/ast-transform.ts
  pnpm-lock.yaml
  tests/fixtures/macro-test/tests/integration/components/macro-unless-test.js
Labels: bug

#1974 esbuild-resolver: handle relative imports in virtual files
  packages/vite/src/esbuild-resolver.ts
Labels: bug

#1978 Webpack: close the compiler
  packages/webpack/src/ember-webpack.ts
Labels: bug

#1981 Revert "Webpack: close the compiler"
  packages/webpack/src/ember-webpack.ts
Labels: bug

#1955 Remove template-only components compilation from Stage 2
  packages/compat/src/audit/babel-visitor.ts
  packages/compat/src/compat-app.ts
  packages/core/src/app-files.ts
  packages/vite/src/hbs.ts
  test-packages/support/audit-assertions.ts
  tests/scenarios/compat-route-split-test.ts
  tests/scenarios/compat-template-colocation-test.ts
Labels: enhancement

#1984 narrow the audit exception for vite internals
  packages/compat/src/audit/babel-visitor.ts
Labels: internal

#1985 Move rewritten app to ./tmp
  packages/compat/src/compat-addons.ts
  packages/compat/src/standalone-addon-build.ts
  tests/addon-template/vite.config.mjs
  tests/app-template/vite.config.mjs
  tests/scenarios/compat-app-html-attributes-test.ts
  tests/scenarios/compat-exclude-dot-files-test.ts
  tests/scenarios/compat-renaming-test.ts
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/compat-template-colocation-test.ts
  tests/scenarios/watch-mode-test.ts
  tests/ts-app-template-classic/vite.config.mjs
  tests/ts-app-template/vite.config.mjs
Labels: internal

#1969 Update `fast-sourcemap-concat` to remove dependency `lodash.template` for consumer apps (security vulnerability)
  packages/compat/package.json
  packages/core/package.json
  pnpm-lock.yaml
  test-packages/sample-transforms/package.json
Labels: bug

#1992 add missing initiative sponsors to the Readme
  README.md
Labels: internal

#2000 Update typescript and fix issues with Typescript 5.5
  package.json
  packages/shared-internals/src/rewritten-package-cache.ts
  pnpm-lock.yaml
Labels: internal

#1996 Merge stable into main
  .github/actions/setup/action.yml
  .github/workflows/ci.yml
  .npmrc
  CHANGELOG.md
  package.json
  packages/compat/package.json
  packages/core/package.json
  packages/macros/package.json
  packages/macros/src/macros-config.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  pnpm-lock.yaml
  test-packages/sample-transforms/package.json
Labels: internal

#2005 unique-id helper import based on ember-source version
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/resolver-transform.ts
  packages/compat/tests/audit.test.ts
  tests/scenarios/compat-resolver-test.ts
Labels: bug

#2006 Virtual entrypoint export modules
  packages/core/src/virtual-entrypoint.ts
  tests/addon-template/tests/dummy/app/app.js
  tests/app-template/app/app.js
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/compat-template-colocation-test.ts
  tests/ts-app-template/app/app.ts
  tests/ts-app-template/types/global.d.ts
  tests/ts-app-template/types/ts-app-template/entry.d.ts
Labels: enhancement

#2007 Add just the necessary files to rollup watch mode
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-keep-assets.ts
  packages/addon-dev/src/rollup-public-entrypoints.ts
Labels: breaking

#2008 Merge stable into main
  CHANGELOG.md
  packages/compat/package.json
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/resolver-transform.ts
  packages/compat/tests/audit.test.ts
  packages/core/package.json
  packages/macros/package.json
  packages/shared-internals/package.json
  packages/webpack/package.json
  tests/scenarios/compat-resolver-test.ts
Labels: internal
