Repository embroider-build/embroider, pull requests merged in 2024-09, with the labels that each got.

#2062 Keep app dir
  packages/compat/package.json
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/compat/src/dependency-rules.ts
  packages/compat/src/resolver-transform.ts
  packages/compat/tests/audit.test.ts
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-entrypoint.ts
  packages/core/src/virtual-route-entrypoint.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/colocation.ts
  pnpm-lock.yaml
  tests/addon-template/tests/dummy/app/index.html
  tests/app-template/app/index.html
  tests/app-template/package.json
  tests/fixtures/macro-sample-addon/tests/dummy/app/index.html
  tests/scenarios/compat-addon-classic-features-test.ts
  tests/scenarios/compat-dummy-app-test.ts
  tests/scenarios/compat-exclude-dot-files-test.ts
  tests/scenarios/compat-preprocessors-test.ts
  tests/scenarios/compat-route-split-test.ts
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/compat-template-colocation-test.ts
  tests/scenarios/core-resolver-test.ts
  tests/ts-app-template/app/index.html
  tests/ts-app-template/package.json
Labels: enhancement

#2092 Don't move index.html
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  tests/addon-template/tests/dummy/index.html
  tests/app-template/index.html
  tests/scenarios/compat-addon-classic-features-test.ts
  tests/scenarios/compat-app-html-attributes-test.ts
  tests/ts-app-template/index.html
Labels: breaking

#2094 make CommandWatcher dump logs at shutdown() when a command has failed
  tests/scenarios/helpers/command-watcher.ts
Labels: internal

#2095 Update scenario-tester
  pnpm-lock.yaml
  tests/scenarios/package.json
Labels: internal

#2101 Merge stable
  .gitignore
  CHANGELOG.md
  README.md
  package.json
  packages/compat/package.json
  packages/compat/src/addon-dependency-rules/ember-power-select-with-create.ts
  packages/compat/src/resolver-transform.ts
  packages/core/package.json
  packages/core/src/virtual-route-entrypoint.ts
  packages/macros/package.json
  packages/shared-internals/package.json
  packages/shared-internals/src/ember-standard-modules.ts
  packages/util/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
Labels: internal

#2102 User-controlled babel config
  packages/compat/babel.js
  packages/compat/package.json
  packages/compat/src/audit.ts
  packages/compat/src/babel.ts
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/compat/src/detect-babel-plugins.ts
  packages/compat/src/rename-require-plugin.ts
  packages/compat/tests/audit.test.ts
  packages/core/package.json
  packages/core/src/module-resolver.ts
  packages/core/src/options.ts
  packages/core/src/portable-babel-config.ts
  packages/core/src/portable-babel-launcher.ts
  packages/core/tests/portable-babel-config.test.ts
  packages/macros/package.json
  packages/shared-internals/src/babel-filter.ts
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/metadata.ts
  packages/webpack/src/ember-webpack.ts
  pnpm-lock.yaml
  test-packages/support/transpiler.ts
  tests/addon-template/babel.config.cjs
  tests/app-template/babel.config.cjs
  tests/app-template/package.json
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
  tests/scenarios/package.json
  tests/ts-app-template-classic/babel.config.cjs
  tests/ts-app-template/babel.config.cjs
Labels: breaking

#2104 Derive default resolver config
  packages/compat/src/babel-plugin-adjust-imports.ts
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/resolver-transform.ts
  packages/compat/tests/audit.test.ts
  packages/core/src/index.ts
  packages/core/src/module-resolver-options.ts
  packages/core/src/module-resolver.ts
  packages/core/src/resolver-loader.ts
  packages/core/src/virtual-entrypoint.ts
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
Labels: enhancement

#2106 add macros plugins with default config rather than no plugins at all
  packages/compat/src/babel.ts
  tests/scenarios/compat-resolver-test.ts
Labels: bug

#2108 Adding forced v2 packages feature
  packages/shared-internals/src/package.ts
Labels: enhancement

#2088 Implement ember's component-template-resolving deprecation
  packages/core/package.json
  packages/core/src/module-resolver.ts
  packages/core/src/virtual-content.ts
  pnpm-lock.yaml
  tests/scenarios/core-resolver-test.ts
Labels: bug

#2124 moduleResolution nodenext
  package.json
  packages/addon-dev/package.json
  packages/compat/package.json
  packages/core/package.json
  packages/core/src/measure-concat.ts
  packages/macros/package.json
  packages/macros/src/macros-config.ts
  packages/shared-internals/package.json
  packages/vite/jest.config.js
  packages/vite/package.json
  packages/vite/src/assets.ts
  packages/vite/src/content-for.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/optimize-deps.ts
  packages/vite/src/request.ts
  packages/vite/src/resolver.ts
  packages/vite/src/scripts.ts
  packages/vite/tests/optimize-deps.test.ts
  packages/webpack/src/ember-webpack.ts
  pnpm-lock.yaml
  test-packages/support/package.json
  tests/scenarios/helpers/v2-addon.ts
  tsconfig.json
Labels: internal

#2121 backport #1855 addon-dev: incremental updates to output
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/addon-dev/src/rollup-hbs-plugin.ts
  packages/addon-dev/src/rollup-incremental-plugin.ts
  packages/addon-dev/src/rollup.ts
  packages/shared-internals/src/colocation.ts
  packages/shared-internals/src/index.ts
  pnpm-lock.yaml
  tests/scenarios/v2-addon-dev-watch-test.ts
Labels: enhancement

#2122 speedup windows ci on stable
  .github/workflows/ci.yml
  packages/shared-internals/src/paths.ts
  tests/scenarios/compat-renaming-test.ts
  tests/scenarios/core-resolver-test.ts
Labels: bug

#2127 Bump jsdom to fix punycode deprecation messages from tr46, psl, and whatwg-url
  packages/compat/package.json
  packages/core/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  tests/scenarios/package.json
Labels: bug
