Repository embroider-build/embroider, pull requests merged in 2024-07, with the labels that each got.

#2012 Empty packages as valid v2 addons
  packages/compat/src/empty-package-tree.ts
Labels: bug

#1931 update scenario-tester
  packages/util/testem.js
  pnpm-lock.yaml
  test-packages/sample-transforms/testem.js
  test-packages/support/testem-config.ts
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
  tests/scenarios/package.json
Labels: internal

#2015 update github actions
  .github/actions/setup/action.yml
  .github/workflows/ci.yml
Labels: internal

#1930 create a smoke test for the widest possible matrix
  pnpm-lock.yaml
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/package.json
  tests/scenarios/scenarios.ts
  tests/scenarios/static-app-test.ts
Labels: internal

#2017 update vite to have a minimum version of 5.2
  packages/vite/package.json
  pnpm-lock.yaml
Labels: enhancement

#2030 Merge stable
  .github/workflows/ci.yml
  CHANGELOG.md
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-keep-assets.ts
  packages/addon-dev/src/rollup-public-entrypoints.ts
  packages/compat/package.json
  packages/compat/src/empty-package-tree.ts
  packages/util/package.json
  packages/util/testem.js
  pnpm-lock.yaml
  test-packages/sample-transforms/package.json
  test-packages/sample-transforms/testem.js
  test-packages/support/suite-setup-util.ts
  test-packages/support/testem-config.ts
  tests/addon-template/package.json
  tests/scenarios/compat-stage2-test.ts
  tests/scenarios/macro-test.ts
  tests/scenarios/package.json
  tests/scenarios/scenarios.ts
  tests/scenarios/static-app-test.ts
Labels: internal

#1966 New config module, warning message
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/options.ts
  tests/fixtures/macro-sample-addon/ember-cli-build.js
  tests/fixtures/macro-test/ember-cli-build.js
  tests/scenarios/macro-test.ts
Labels: enhancement

#2047 Add semver to power select with create
  packages/compat/src/addon-dependency-rules/ember-power-select-with-create.ts
Labels: bug

#2033 Remove deprecations warnings in resolver transform
  packages/compat/src/resolver-transform.ts
Labels: bug

#2053 fix for esbuild finding helpers and components from app-tree-merging in templates
  packages/core/src/module-resolver.ts
  pnpm-lock.yaml
  tests/scenarios/package.json
  tests/scenarios/vite-internals-test.ts
Labels: bug

#1842 [beta] template-tag code mod
  packages/compat/package.json
  packages/compat/src/index.ts
  packages/compat/src/template-tag-codemod.ts
  pnpm-lock.yaml
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2055 document templateTagCodemod usage
  README.md
Labels: documentation

#2058 Set the packageManager field
  .github/actions/setup/action.yml
  package.json
Labels: internal
