Repository embroider-build/embroider, pull requests merged in 2024-02, with the labels that each got.

#1781 Fix failing addon-dev-js test on stable
  tests/scenarios/v2-addon-dev-test.ts
Labels: internal

#1777 Backport #1642 to stable: Allow for more flexible addon-dev appReexports
  packages/addon-dev/src/rollup-app-reexports.ts
  packages/addon-dev/src/rollup.ts
  tests/scenarios/v2-addon-dev-typescript-test.ts
Labels: enhancement

#1763 Add new watches API
  packages/core/src/node-resolve.ts
  packages/core/src/virtual-content.ts
  packages/hbs-loader/src/index.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/virtual-loader.ts
Labels: enhancement

#1784 Bump content-tag and add inline_source_map option for rollup and vite
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/vite/package.json
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/template-tag.ts
  pnpm-lock.yaml
Labels: enhancement

#1786 Bump content-tag and add inline_source_map option for rollup and vite
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/vite/package.json
  packages/vite/src/template-tag.ts
  pnpm-lock.yaml
Labels: enhancement

#1790 Update @embroider/macros README.md real-world examples
  packages/macros/README.md
Labels: bug

#1791 docs(porting-addons-to-v2): Explain no-unpublished-required issue
  docs/porting-addons-to-v2.md
Labels: documentation

#1787 Fix source map option not being passed to plugin
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/addon-dev/src/rollup.ts
Labels: bug

#1744 control ember build through vite
  packages/vite/index.d.ts
  packages/vite/index.mjs
  packages/vite/src/build.ts
  tests/scenarios/vite-app-test.ts
  tests/vite-app/package.json
  tests/vite-app/vite.config.mjs
Labels: enhancement

#1817 pin ember-data to fix issue in CI
  pnpm-lock.yaml
  tests/scenarios/package.json
Labels: internal

#1816 Remove silent option from ember build in compatPrebuild
  packages/vite/src/build.ts
Labels: bug

#1820 [stable] Pin ember-data to fix issue in CI
  pnpm-lock.yaml
  tests/scenarios/package.json
Labels: internal

#1824 update release-plan
  .github/workflows/publish-stable.yml
  .github/workflows/release-plan-preview.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#1825 Merge stable into main
  .github/workflows/publish-stable.yml
  .github/workflows/release-plan-preview.yml
  .release-plan.json
  CHANGELOG.md
  RELEASE.md
  package.json
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/addon-dev/src/rollup.ts
  packages/compat/package.json
  packages/core/package.json
  packages/macros/package.json
  packages/macros/src/babel/evaluate-json.ts
  packages/macros/tests/babel/eval.test.ts
  packages/macros/tests/babel/macro-condition.test.ts
  packages/shared-internals/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
Labels: internal

#1794 Refactor the resolve function to be the only public api to module-resolver
  packages/compat/src/compat-app-builder.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/request.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/webpack-resolver-plugin.ts
  pnpm-lock.yaml
Labels: breaking

#1819 Add a new prebuild function with strict defaults
  packages/compat/src/default-pipeline.ts
  packages/compat/src/index.ts
  tests/vite-app/ember-cli-build.js
Labels: enhancement
