Repository embroider-build/embroider, pull requests merged in 2024-11, with the labels that each got.

#2164 Support v2 ember-source
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
Labels: enhancement

#2166 Fix gjs/gts sourcemaps -- we accidentally unlocked really good DX
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/addon-dev/src/rollup.ts
  pnpm-lock.yaml
Labels: breaking

#2179 removing unused functionality in default-pipeline
  packages/compat/src/default-pipeline.ts
  packages/compat/src/index.ts
  packages/core/src/index.ts
  packages/core/src/to-broccoli-plugin.ts
Labels: bug

#2184 Updating @types/node
  packages/compat/package.json
  packages/core/package.json
  packages/hbs-loader/package.json
  packages/macros/package.json
  packages/macros/tests/babel/helpers.ts
  packages/vite/src/assets.ts
  packages/webpack/package.json
  pnpm-lock.yaml
  test-packages/support/package.json
Labels: internal

#2188 Module request cleanup
  packages/core/src/index.ts
  packages/core/src/module-request.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/request.ts
  packages/vite/src/resolver.ts
  packages/webpack/src/webpack-resolver-plugin.ts
Labels: internal
