Repository embroider-build/embroider, pull requests merged in 2025-05, with the labels that each got.

#2467 upstream changed generated identifiers and this test is fragile
  packages/macros/tests/babel/import-sync.test.ts
  pnpm-lock.yaml
Labels: internal

#2464 Don't run terser when --mode=test
  packages/vite/src/ember.ts
Labels: bug

#2469 fix: ensure minify can be disabled
  packages/vite/src/ember.ts
Labels: bug

#2474 Allow declarations plugin to have its command customized
  packages/addon-dev/src/rollup-declarations.ts
  packages/addon-dev/src/rollup.ts
Labels: enhancement

#2481 Vite build should resolve ember-cli from working dir
  packages/vite/src/build.ts
Labels: bug

#2482 Propagate other plugin's custom metadata
  packages/vite/src/request.ts
Labels: bug

#2489 [template-tag-codemod] Add version to `--nativeLexicalThis` & update ReadMe
  packages/template-tag-codemod/README.md
  packages/template-tag-codemod/src/cli.ts
Labels: documentation

#2492 Update porting-addons-to-v2.md
  docs/porting-addons-to-v2.md
Labels: documentation
