Repository embroider-build/embroider, pull requests merged in 2025-03, with the labels that each got.

#2349 update release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#2352 Babel import util updates
  packages/compat/package.json
  packages/compat/src/babel-plugin-adjust-imports.ts
  packages/compat/src/resolver-transform.ts
  packages/macros/package.json
  packages/macros/src/babel/macros-babel-plugin.ts
  packages/macros/src/babel/state.ts
  packages/macros/tests/babel/eval.test.ts
  packages/macros/tests/babel/import-sync.test.ts
  packages/shared-internals/package.json
  packages/shared-internals/src/template-colocation-plugin.ts
  packages/template-tag-codemod/package.json
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
Labels: bug

#2354 Fix addon-dev's declarations plugin when glint fails
  packages/addon-dev/src/rollup-declarations.ts
Labels: bug

#2356 build config-meta-loader into dist folder
  packages/config-meta-loader/.gitignore
  packages/config-meta-loader/package.json
  packages/config-meta-loader/tsconfig.json
Labels: internal

#2358 fix gitignore for switching between stable and main
  .gitignore
  packages/vite/.gitignore
Labels: internal

#2357 fix index.ts component resolving
  packages/core/src/node-resolve.ts
  tests/scenarios/typescript-app-test.ts
Labels: bug

#2344 move most of the implementation of staticInvokables to core
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/options.ts
  packages/core/src/options.ts
Labels: bug

#2363 Add "merge-history" subcommand to codemod
  packages/template-tag-codemod/README.md
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/merge-history.ts
Labels: enhancement

#2367 Adding more detail in template-tag readme
  packages/template-tag-codemod/README.md
Labels: documentation

#2368 Optimize reverseSearchAppTree
  packages/core/src/module-resolver.ts
Labels: bug

#2369 Merge stable into main
  .gitignore
  CHANGELOG.md
  packages/addon-dev/src/rollup-declarations.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/template-tag-codemod/src/index.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/request.ts
  tests/scenarios/typescript-app-test.ts
Labels: internal

#2371 Merge stable into main
  CHANGELOG.md
Labels: internal

#2370 Handle name collisions when using `--addNameToTemplateOnly`
  packages/template-tag-codemod/src/index.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: bug

#2380 mark template-codemod as a stable 1.0.0 release
  packages/template-tag-codemod/package.json
Labels: breaking

#2372 always use source maps for gjs in vite
  packages/vite/package.json
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/template-tag.ts
  pnpm-lock.yaml
Labels: enhancement

#2388 Add support for Ember 4.4
  packages/compat/src/compat-adapters/ember-source.ts
  tests/scenarios/scenarios.ts
Labels: enhancement

#2406 Merge stable into main
  packages/macros/src/babel/evaluate-json.ts
  packages/macros/tests/babel/macro-condition.test.ts
Labels: internal

#2413 Deprecate @embroider/util
  docs/replacing-component-helper.md
  packages/util/README.md
  packages/util/package.json
  pnpm-lock.yaml
  tests/scenarios/package.json
  tests/scenarios/util-test.ts
Labels: breaking

#2412 Update @glimmer/syntax types
  packages/addon-dev/package.json
  packages/compat/package.json
  packages/core/package.json
  packages/template-tag-codemod/package.json
  pnpm-lock.yaml
  test-packages/support/package.json
Labels: internal

#2411 esbuild backchannel fix
  packages/vite/src/backchannel.ts
  packages/vite/src/esbuild-request.ts
  packages/vite/src/esbuild-resolver.ts
  packages/vite/src/resolver.ts
  tests/scenarios/vite-internals-test.ts
Labels: bug

#2320 convert from yargs to commander
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/index.ts
  pnpm-lock.yaml
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2414 update remaining template tag codemod tests
  tests/scenarios/template-tag-codemod-test.ts
Labels: internal
