Repository embroider-build/embroider, pull requests merged in 2025-10, with the labels that each got.

#2552 Warn if `{{rootURL}}` is present in index.html
  packages/vite/.gitignore
  packages/vite/package.json
  packages/vite/src/ember.ts
  packages/vite/src/warn-root-url.ts
  packages/vite/tests/warn-root-url.test.js
  pnpm-lock.yaml
Labels: enhancement

#2571 Drop `node:` prefix on imports in app-ember-satisfies to accomodate node < 16
  .github/workflows/ci.yml
  packages/macros/package.json
  packages/macros/smoke-test.js
  packages/macros/src/babel/app-ember-satisfies.ts
  packages/macros/tests/babel/import-sync.test.ts
Labels: bug

#2576 don't break SSR with legacy-inspector-support
  packages/legacy-inspector-support/src/common-implementation.js
Labels: bug

#2575 simplify gitignore for @embroider/vite
  packages/vite/.gitignore
Labels: internal

#2581 fix error on windows build with lazy engines or re-written packages
  packages/vite/src/resolver.ts
Labels: bug
