Repository embroider-build/embroider, pull requests merged in 2025-02, with the labels that each got.

#2240 move tests/scenarios to a TS sub-project
  tests/scenarios/.gitignore
  tests/scenarios/tsconfig.json
  tsconfig.json
Labels: internal

#2244 add a simple deprecation for staticAddonTrees and staticAddonTestSupportTrees
  packages/compat/src/options.ts
Labels: documentation

#2256 remove staticAddonTrees and staticAddonTestSupportTrees
  packages/compat/src/options.ts
  packages/compat/src/v1-addon.ts
  tests/scenarios/compat-exclude-dot-files-test.ts
  tests/scenarios/compat-template-colocation-test.ts
  tests/scenarios/stage1-test.ts
Labels: breaking

#2260 Vite config overridability
  packages/vite/package.json
  packages/vite/src/classic-ember-support.ts
  packages/vite/src/ember.ts
  pnpm-lock.yaml
Labels: bug

#2261 Fix bug in import deduplication in template-tag-codemod
  packages/template-tag-codemod/src/index.ts
Labels: bug

#2262 Update ts-app-template to match app-template
  tests/ts-app-template/ember-cli-build.js
Labels: internal

#2263 template-tag-codemod test coverage and robustness fixes
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/identify-render-tests.ts
  packages/template-tag-codemod/src/index.ts
  pnpm-lock.yaml
  test-packages/support/codemod-assertions.ts
  test-packages/support/package.json
  tests/scenarios/package.json
  tests/scenarios/template-tag-codemod-test.ts
Labels: bug

#2265 Fix package jsons
  packages/broccoli-side-watch/package.json
  packages/reverse-exports/package.json
  packages/vite/package.json
Labels: bug

#2267 Fix release plan setup for main
  packages/broccoli-side-watch/package.json
  packages/core/package.json
  packages/reverse-exports/package.json
  packages/router/package.json
  packages/vite/package.json
Labels: internal

#2268 remove the last few references to staticAddonTrees
  packages/compat/src/options.ts
  tests/scenarios/compat-route-split-test.ts
  tests/scenarios/router-test.ts
Labels: bug

#2272 Cleanup v2 addon rollup warnings, update virtual parkages list
  packages/addon-dev/src/rollup-gjs-plugin.ts
  packages/shared-internals/src/ember-standard-modules.ts
Labels: bug

#2274 remove duplicate options default
  packages/compat/src/options.ts
Labels: bug

#2271 Template tag codemod stability fixes
  README.md
  packages/template-tag-codemod/src/index.ts
Labels: enhancement

#2276 make sure all packages stay within pre-release
  packages/addon-dev/package.json
  packages/addon-shim/package.json
  packages/babel-loader-9/package.json
  packages/compat/package.json
  packages/config-meta-loader/package.json
  packages/hbs-loader/package.json
  packages/macros/package.json
  packages/shared-internals/package.json
  packages/template-tag-codemod/package.json
  packages/util/package.json
Labels: internal

#2264 Improved codemod scope management
  packages/compat/src/resolver-transform.ts
  packages/template-tag-codemod/.gitignore
  packages/template-tag-codemod/README.md
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/identify-render-tests.ts
  packages/template-tag-codemod/src/index.ts
  packages/template-tag-codemod/src/replace-this-transform.ts
  packages/template-tag-codemod/tsconfig.json
  test-packages/support/codemod-assertions.ts
  tests/scenarios/template-tag-codemod-test.ts
  tsconfig.json
Labels: bug

#2279 fix failure on first-run and auto-apply package.json updates
  packages/template-tag-codemod/src/index.ts
Labels: bug

#2282 Customizable renaming support in template-tag-codemod
  packages/compat/src/resolver-transform.ts
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/default-renaming.ts
  packages/template-tag-codemod/src/index.ts
  pnpm-lock.yaml
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2281 Include version in prebuild output
  packages/compat/src/compat-app-builder.ts
  packages/template-tag-codemod/src/index.ts
Labels: bug

#2283 Finish implementing --renamingRules for template-tag-codemod
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/index.ts
  pnpm-lock.yaml
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2291 Fix nodeResolve's support for package.json exports on stable
  .gitignore
  packages/compat/src/audit.ts
  packages/compat/src/compat-app-builder.ts
  packages/compat/tests/audit.test.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  pnpm-lock.yaml
Labels: bug

#2285 Introduce EMBROIDER_WORKING_DIRECTORY env var for concurrent builds
  packages/shared-internals/src/working-dir.ts
Labels: enhancement

#2290 Add docs for EMBROIDER_WORKING_DIRECTORY
  README.md
Labels: documentation

#2286 Workaround babel evaluation bug
  packages/macros/src/babel/evaluate-json.ts
  packages/macros/tests/babel/eval.test.ts
Labels: bug

#2185 this-property-fallback is not a possibility on ember >=4
  packages/compat/src/resolver-transform.ts
  tests/scenarios/compat-resolver-test.ts
Labels: bug

#2295 Ember canary fixes
  packages/vite/src/ember.ts
  pnpm-lock.yaml
  tests/scenarios/package.json
  tests/scenarios/router-test.ts
  tests/scenarios/scenarios.ts
  tests/scenarios/typescript-app-test.ts
  tests/ts-app-template/vite.config.mjs
Labels: bug

#2294 Merge stable into main
  CHANGELOG.md
  packages/compat/src/resolver-transform.ts
  packages/macros/src/babel/evaluate-json.ts
  packages/macros/tests/babel/eval.test.ts
  tests/scenarios/compat-resolver-test.ts
Labels: internal

#2296 handle empty pojo arg to precompileTemplate
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/identify-render-tests.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: bug

#2298 Fix staticInvokables resolution of ts components
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  tests/scenarios/typescript-app-test.ts
Labels: bug

#2249 Expose macros config in babel
  packages/compat/src/babel.ts
  packages/macros/README.md
  packages/macros/package.json
  packages/macros/src/babel.ts
  packages/macros/tests/babel/dependency-satisfies.test.ts
  packages/macros/tests/babel/get-config.test.ts
Labels: enhancement

#2299 Add ability to configure MiniCssExtractPlugin
  packages/webpack/src/ember-webpack.ts
  packages/webpack/src/options.ts
Labels: enhancement

#2305 Fix vendor ember-template-compiler.js on v2 ember-source
  packages/compat/src/compat-app.ts
Labels: bug

#2307 Share "this" re-bindings within the same scope
  packages/template-tag-codemod/src/identify-render-tests.ts
  packages/template-tag-codemod/src/index.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: bug

#2309 codemod: support all the legacy inline hbs module names
  packages/template-tag-codemod/src/detect-inline-hbs.ts
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/identify-render-tests.ts
  packages/template-tag-codemod/src/index.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2312 codemod: document ember-css-modules workaround
  packages/template-tag-codemod/README.md
Labels: documentation

#2317 Vite 6.2 includes breaking changes to esbuild types
  packages/vite/package.json
  pnpm-lock.yaml
Labels: internal

#2319 template-tag-codemod: only reuse ember prebuild if you explicitly pass the option to do so
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/index.ts
Labels: enhancement

#2327 Improve template-tag-codemod error reporting
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/index.ts
  pnpm-lock.yaml
Labels: enhancement

#2328 Skip and report non-native-class syntax components
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/index.ts
  test-packages/support/codemod-assertions.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2330 Handle render tests that define the template outside the render call
  packages/template-tag-codemod/src/identify-render-tests.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: enhancement

#2332 Fix lexical this polyfill when "this" has no tail
  packages/template-tag-codemod/src/index.ts
  packages/template-tag-codemod/src/replace-this-transform.ts
  tests/scenarios/template-tag-codemod-test.ts
Labels: bug
