Repository embroider-build/embroider, pull requests merged in 2025-04, with the labels that each got.

#2237 Pass along options to resolve
  packages/addon-dev/src/rollup-hbs-plugin.ts
Labels: bug

#2420 reset addon-shim to have the same version as stable
  packages/addon-shim/package.json
Labels: enhancement

#2422 set addon-shim to release a pre-minor
  packages/addon-shim/package.json
Labels: internal

#2426 fix types on stable
  packages/compat/package.json
  packages/core/package.json
  packages/macros/package.json
  pnpm-lock.yaml
  tests/scenarios/package.json
Labels: internal

#2425 Adding a compat adapter for ember-fetch
  packages/compat/src/compat-adapters/ember-fetch.ts
Labels: enhancement

#2429 Merge stable into main
  CHANGELOG.md
  packages/addon-dev/src/rollup-hbs-plugin.ts
  packages/compat/src/compat-adapters/ember-fetch.ts
Labels: internal

#2433 Fix issue occuring when some consumers of @embroider/macros specify extensions for macros' content via require/import
  packages/macros/package.json
Labels: bug

#2436 Fix resolving EmberCLI in vite prebuild
  packages/vite/src/build.ts
Labels: bug

#2435 Fix issue when your library has no prior app-js entry in package.json
  packages/addon-dev/src/rollup-app-reexports.ts
Labels: bug

#2443 Widen Range for @ember/test-waiters
  packages/router/package.json
  pnpm-lock.yaml
Labels: bug

#2324 move embroider compat to a tsconfig reference project
  packages/compat/.gitignore
  packages/compat/package.json
  packages/compat/tsconfig.json
  tsconfig.json
Labels: internal

#2451 move core to a tsconfig project
  packages/core/.gitignore
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/virtual-entrypoint.ts
  packages/core/tests/portable.test.ts
  packages/core/tsconfig.json
  packages/macros/tests/babel/module-exists.test.ts
  pnpm-lock.yaml
  test-packages/support/audit-assertions.ts
  test-packages/support/package.json
  test-packages/support/transpiler.ts
  tsconfig.json
Labels: internal

#2450 convert reverse-exports to a tsconfig project
  packages/reverse-exports/.gitignore
  packages/reverse-exports/jest.config.js
  packages/reverse-exports/package.json
  packages/reverse-exports/tsconfig.json
  pnpm-lock.yaml
  tsconfig.json
Labels: internal

#2449 Major speedup of reverse-exports
  packages/reverse-exports/package.json
  packages/reverse-exports/src/index.ts
  packages/reverse-exports/tests/reverse-exports.test.ts
  pnpm-lock.yaml
Labels: bug

#2462 Terser by default in prod
  packages/vite/src/ember.ts
  pnpm-lock.yaml
  tests/app-template-minimal/package.json
  tests/app-template/package.json
  tests/ts-app-template/package.json
Labels: enhancement
