Repository embroider-build/embroider, pull requests merged in 2025-01, with the labels that each got.

#2223 Remove app meta
  packages/addon-shim/src/index.ts
  packages/compat/package.json
  packages/compat/src/audit-cli.ts
  packages/compat/src/audit.ts
  packages/compat/src/audit/options.ts
  packages/compat/src/compat-adapters/ember-cli-fastboot.ts
  packages/compat/src/compat-adapters/ember-cli-mirage.ts
  packages/compat/src/compat-app.ts
  packages/compat/tests/audit.test.ts
  packages/core/src/index.ts
  packages/core/src/module-resolver.ts
  packages/core/src/packager.ts
  packages/core/tests/packager.test.ts
  packages/shared-internals/src/colocation.ts
  packages/shared-internals/src/index.ts
  packages/shared-internals/src/metadata.ts
  packages/shared-internals/src/package.ts
  packages/shared-internals/src/rewritten-package-cache.ts
  packages/shared-internals/tests/template-colocation-plugin.test.ts
  packages/webpack/src/ember-webpack.ts
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
  tests/scenarios/core-resolver-test.ts
Labels: breaking

#2226 template-tag-codemod
  .eslintignore
  .prettierignore
  packages/compat/src/index.ts
  packages/compat/src/resolver-transform.ts
  packages/core/src/module-resolver.ts
  packages/core/src/node-resolve.ts
  packages/template-tag-codemod/.eslintignore
  packages/template-tag-codemod/.gitignore
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/index.ts
  packages/template-tag-codemod/src/prebuild.ts
  packages/template-tag-codemod/src/route-template-transform.ts
  packages/template-tag-codemod/tsconfig.json
  pnpm-lock.yaml
  tests/scenarios/compat-resolver-test.ts
Labels: enhancement

#2227 Merge stable into main
  CHANGELOG.md
  README.md
  packages/addon-dev/jest.config.js
  packages/addon-dev/package.json
  packages/addon-dev/src/rollup-declarations.ts
  packages/addon-dev/src/rollup.ts
  packages/addon-dev/tests/declarations.test.ts
  packages/compat/package.json
  packages/compat/src/compat-app-builder.ts
  packages/compat/src/compat-app.ts
  packages/compat/src/options.ts
  packages/compat/src/v1-addon.ts
  packages/core/package.json
  packages/core/src/options.ts
  packages/macros/package.json
  packages/webpack/package.json
  packages/webpack/src/ember-webpack.ts
  pnpm-lock.yaml
  tests/scenarios/compat-route-split-test.ts
  tests/scenarios/compat-template-colocation-test.ts
  tests/scenarios/router-test.ts
Labels: internal

#2232 move @embroider/vite typescript build to a project reference
  packages/core/package.json
  packages/core/src/messages.ts
  packages/vite/.gitignore
  packages/vite/index.d.ts
  packages/vite/index.ts
  packages/vite/package.json
  packages/vite/tsconfig.json
  pnpm-lock.yaml
  tsconfig-base.json
  tsconfig.json
Labels: internal

#2231 template-tag-codemod: add support for rendering tests
  packages/template-tag-codemod/package.json
  packages/template-tag-codemod/src/cli.ts
  packages/template-tag-codemod/src/extract-meta.ts
  packages/template-tag-codemod/src/identify-render-tests.ts
  packages/template-tag-codemod/src/index.ts
  packages/template-tag-codemod/src/replace-this-transform.ts
  pnpm-lock.yaml
Labels: enhancement

#2233 Add a builder API to @embroider/compat to support ember commands like `ember test`
  packages/compat/src/default-pipeline.ts
  packages/compat/src/index.ts
  packages/vite/index.ts
  packages/vite/src/build-once.ts
  tests/app-template/ember-cli-build.js
Labels: enhancement

#2235 Fix binary asset support in keepAssets
  packages/addon-dev/src/rollup-keep-assets.ts
  tests/scenarios/v2-addon-dev-test.ts
Labels: bug
